### GENERAL SETTINGS ###

# Site settings
language: "pt-BR"
title: Engarte
author: "Alan Leal"
description: "Assessoria digital para políticos e candidatos."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://engarte.com"

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
#  - "/assets/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"


# Build settings
markdown: kramdown
permalink: /:categories/:title
paginate_path:    "/blog/page:num"
paginate:         5
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
# Plugins
gems:             ["jekyll-sitemap", "jekyll-paginate"]

# Conversion
incremental:      true
